#!/usr/bin/env bash
# Displays content of current directory in list format with dashes
for file in *
do
	if [[ ! "$file" =~ ^\..* && "$file" =~ .*-.* ]]
	then
		name=$(echo "$file" | cut -d '-' -f 2-)
		echo "$name"
	fi
done
